#!/usr/bin/env python3
"""
Builds tabler-auto.css: Tabler's dark theme, applied to data-bs-theme="auto" when
the operating system prefers dark (spec 7.3).

Tabler's compiled CSS has no prefers-color-scheme rule - dark mode is only the
[data-bs-theme=dark] selectors - so a theme that follows the system needs their
twin under a media query. Generated rather than hand-written, so a Tabler upgrade
carries its dark palette across by re-running this.

    scripts/tabler-auto-theme.py <tabler.min.css> <tabler-auto.css>
"""
import pathlib, re, sys

DARK, AUTO = '[data-bs-theme=dark]', '[data-bs-theme=auto]'


def split_top(text, sep):
    """Split on sep outside parentheses and brackets."""
    parts, depth, start = [], 0, 0
    for i, c in enumerate(text):
        if c in '([':
            depth += 1
        elif c in ')]':
            depth -= 1
        elif c == sep and depth == 0:
            parts.append(text[start:i])
            start = i + 1
    parts.append(text[start:])
    return parts


def blocks(css):
    """Yield (prelude, body) for each top-level block."""
    i, n = 0, len(css)
    while i < n:
        open_ = css.find('{', i)
        if open_ < 0:
            return
        depth, j = 1, open_ + 1
        while depth:
            depth += {'{': 1, '}': -1}.get(css[j], 0)
            j += 1
        # A statement before the block (@charset, a licence comment) is not its prelude.
        prelude = re.sub(r'/\*.*?\*/', '', css[i:open_], flags=re.S).rsplit(';', 1)[-1]
        yield prelude.strip(), css[open_ + 1:j - 1]
        i = j


def rewrite(css):
    out = []
    for prelude, body in blocks(css):
        if prelude.startswith('@'):
            # Print stays light, as Tabler intends; other conditions nest as they are.
            if prelude.startswith('@media') and 'print' not in prelude:
                inner = rewrite(body)
                if inner:
                    out.append(f'{prelude}{{{inner}}}')
            continue
        # Only selectors that turn dark on the attribute; a negation of it
        # (":not([data-bs-theme=dark])") would mean the opposite once rewritten.
        selectors = [s.replace(DARK, AUTO) for s in split_top(prelude, ',')
                     if DARK in s and ':not(' not in s]
        if selectors:
            out.append(f'{",".join(selectors)}{{{body}}}')
    return ''.join(out)


source, target = pathlib.Path(sys.argv[1]), pathlib.Path(sys.argv[2])
rules = rewrite(source.read_text())
if not rules:
    sys.exit(f'no {DARK} rules in {source} - has Tabler changed how it does dark mode?')
target.write_text('/* Generated by scripts/tabler-auto-theme.py from tabler.min.css - do not edit. */\n'
                  f'@media screen and (prefers-color-scheme:dark){{{rules}}}\n')
print(f'  {target.name:<20} {target.stat().st_size:>8} bytes')
